name: CI test to build and run the regression tests

on: [pull_request,workflow_dispatch]

jobs:
  run_driver:

    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        fortran-compiler: [gfortran-10, gfortran-11, gfortran-12]

    # Environmental variables
    env:
      NFHOME:      /home/runner/netcdf-fortran
      NFVERSION:   v4.5.3
      driver_ROOT: /home/runner/work/template/template

    # Workflow steps
    steps:

    - name: Checkout code (into ${driver_ROOT})
      uses: actions/checkout@v3

    - name: Install NetCDF C library
      run: sudo apt-get install libnetcdf-dev

    - name: Cache NetCDF Fortran library
      id: cache-netcdf-fortran
      uses: actions/cache@v4
      with:
        path: /home/runner/netcdf-fortran
        key: cache-netcdf-fortran-${{matrix.fortran-compiler}}-${{matrix.build-type}}-key

    - name: Install NetCDF Fortran library
      if: steps.cache-netcdf-fortran.outputs.cache-hit != 'true'
      run: |
        git clone --branch ${NFVERSION} https://github.com/Unidata/netcdf-fortran.git
        cd netcdf-fortran
        ./configure
        make -j
        sudo make install
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NFHOME}/lib

    - name: Build unit tests
      run: |
        cd ${driver_ROOT}/tests
        make driver

    - name: Run unit tests
      run: |
        cd ${driver_ROOT}/tests
        ./driver